import type { Command, CommandState } from './command.js';
import type { CommandHost } from './host.js';

/**
 * The command set.
 *
 * Sectors are assigned once, here, and never move. Feature *variants* live in the
 * feature's parameter panel — a boolean's union/cut/intersect is a field, not three
 * toolbar buttons and not a submenu.
 */

const needsSelection = (kind: 'face' | 'edge' | 'body', what: string) =>
  (state: CommandState) =>
    state.selectionKind === kind && state.selectionCount > 0
      ? true
      : `Select ${what} first`;

const needsModel = (state: CommandState) =>
  state.hasModel ? true : 'Nothing in the model yet';

export function createBuiltinCommands(host: CommandHost): Command[] {
  return [
    // ---------------------------------------------------------------- sketching
    {
      id: 'sketch.new',
      title: 'Sketch',
      hint: 'Start a sketch on a plane',
      icon: '✎',
      contexts: ['face', 'empty'],
      sector: { face: 0 },
      toolbar: { order: 10 },
      keys: ['s'],
      children: ['sketch.onFace', 'sketch.onXY', 'sketch.onXZ', 'sketch.onYZ'],
      enabled: (s) => (s.sketching ? 'Already sketching' : true),
      run: () => {},
    },
    {
      id: 'sketch.onFace',
      title: 'On selected face',
      hint: 'Sketch on the face you have selected',
      icon: '◧',
      contexts: ['face'],
      enabled: (s) => {
        if (s.sketching) return 'Already sketching';
        return s.selectionKind === 'face' && s.selectionCount > 0
          ? true
          : 'Select a flat face first';
      },
      run: async () => { await host.beginSketchOnFace(); },
    },
    {
      id: 'sketch.onXY',
      title: 'Top (XY)',
      hint: 'Sketch on the ground plane',
      icon: '▤',
      contexts: ['empty'],
      enabled: (s) => (s.sketching ? 'Already sketching' : true),
      run: async () => { await host.beginSketch('xy'); },
    },
    {
      id: 'sketch.onXZ',
      title: 'Front (XZ)',
      icon: '▥',
      contexts: ['empty'],
      enabled: (s) => (s.sketching ? 'Already sketching' : true),
      run: async () => { await host.beginSketch('xz'); },
    },
    {
      id: 'sketch.onYZ',
      title: 'Side (YZ)',
      icon: '▧',
      contexts: ['empty'],
      enabled: (s) => (s.sketching ? 'Already sketching' : true),
      run: async () => { await host.beginSketch('yz'); },
    },

    // ---------------------------------------------------------------- sketch tools
    {
      id: 'sketch.line',
      title: 'Line',
      hint: 'Draw connected lines; click the start again to close',
      icon: '╱',
      contexts: ['sketch'],
      sector: { sketch: 0 },
      keys: ['l'],
      enabled: (s) => (s.sketching ? true : 'Open a sketch first'),
      run: () => host.setSketchTool('line'),
    },
    {
      id: 'sketch.rectangle',
      title: 'Rectangle',
      icon: '▭',
      contexts: ['sketch'],
      sector: { sketch: 2 },
      keys: ['r'],
      enabled: (s) => (s.sketching ? true : 'Open a sketch first'),
      run: () => host.setSketchTool('rectangle'),
    },
    {
      id: 'sketch.circle',
      title: 'Circle',
      icon: '○',
      contexts: ['sketch'],
      sector: { sketch: 4 },
      keys: ['o'],
      enabled: (s) => (s.sketching ? true : 'Open a sketch first'),
      run: () => host.setSketchTool('circle'),
    },
    {
      id: 'sketch.select',
      title: 'Select',
      icon: '⬉',
      contexts: ['sketch'],
      sector: { sketch: 6 },
      enabled: (s) => (s.sketching ? true : 'Open a sketch first'),
      run: () => host.setSketchTool('select'),
    },
    {
      id: 'sketch.dimension',
      title: 'Dimension',
      hint: 'Pin a length or radius; click two points, or a circle',
      icon: '↔',
      contexts: ['sketch'],
      sector: { sketch: 1 },
      keys: ['d'],
      enabled: (s) => (s.sketching ? true : 'Open a sketch first'),
      run: () => host.setSketchTool('dimension'),
    },
    {
      id: 'sketch.finish',
      title: 'Finish sketch',
      hint: 'Close the sketch and return to the model',
      icon: '✓',
      contexts: ['sketch', 'always'],
      enabled: (s) => (s.sketching ? true : 'No sketch is open'),
      run: async () => { await host.finishSketch(); },
    },
    {
      id: 'sketch.edit',
      title: 'Edit sketch',
      hint: 'Reopen this sketch for editing',
      icon: '✐',
      contexts: ['tree-item'],
      sector: { 'tree-item': 4 },
      enabled: (s) => {
        if (s.sketching) return 'Finish the current sketch first';
        return s.focusedFeature ? true : 'Select a sketch in the tree';
      },
      run: async () => { await host.editSketch(); },
    },
    {
      id: 'sketch.delete',
      title: 'Delete',
      hint: 'Remove the selected sketch geometry',
      icon: '␡',
      contexts: ['sketch'],
      sector: { sketch: 5 },
      enabled: (s) => (s.sketching ? true : 'Open a sketch first'),
      run: () => { host.deleteSketchSelection(); },
    },
    {
      id: 'build.solid',
      title: 'Build',
      hint: 'Turn a sketch into a solid',
      icon: '⬒',
      contexts: ['always'],
      toolbar: { order: 11 },
      children: ['sketch.extrude', 'build.revolve', 'build.sweep', 'build.loft'],
      enabled: (s) => (s.sketching ? 'Finish the sketch first' : true),
      run: () => {},
    },
    {
      id: 'sketch.extrude',
      title: 'Extrude',
      hint: 'Sweep the sketch straight out',
      icon: '⬒',
      contexts: ['always'],
      keys: ['e'],
      enabled: (s) => (s.sketching ? 'Finish the sketch first' : true),
      run: async () => { await host.extrudeSketch(); },
    },
    {
      id: 'build.revolve',
      title: 'Revolve',
      hint: 'Spin the sketch around an axis',
      icon: '↻',
      contexts: ['always'],
      enabled: (s) => (s.sketching ? 'Finish the sketch first' : true),
      run: async () => { await host.addSolidFeature('revolve'); },
    },
    {
      id: 'build.sweep',
      title: 'Sweep',
      hint: 'Run the sketch along a path drawn as a second sketch',
      icon: '⤳',
      contexts: ['always'],
      enabled: (s) => (s.sketching ? 'Finish the sketch first'
        : s.featureCount >= 2 ? true : 'Draw a profile and a path first'),
      run: async () => { await host.addSolidFeature('sweep'); },
    },
    {
      id: 'build.loft',
      title: 'Loft',
      hint: 'Blend two or more sketches into one solid',
      icon: '⧗',
      contexts: ['always'],
      enabled: (s) => (s.sketching ? 'Finish the sketch first'
        : s.featureCount >= 2 ? true : 'Draw at least two sections first'),
      run: async () => { await host.addSolidFeature('loft'); },
    },

    // ---------------------------------------------------------------- primitives
    {
      id: 'create.shape',
      title: 'New shape',
      hint: 'Add a box, cylinder or sphere',
      icon: '◇',
      contexts: ['empty', 'always'],
      sector: { empty: 0 },
      toolbar: { order: 20 },
      children: ['primitive.box', 'primitive.cylinder', 'primitive.sphere'],
      enabled: () => true,
      run: () => {}, // a group: opening the flyout is the action
    },
    {
      id: 'primitive.box',
      title: 'Box',
      hint: 'Add a box',
      icon: '▣',
      contexts: ['empty', 'always'],
      enabled: () => true,
      run: async () => { await host.addPrimitive('box'); },
    },
    {
      id: 'primitive.cylinder',
      title: 'Cylinder',
      hint: 'Add a cylinder',
      icon: '⬭',
      contexts: ['empty', 'always'],
      enabled: () => true,
      run: async () => { await host.addPrimitive('cylinder'); },
    },
    {
      id: 'primitive.sphere',
      title: 'Sphere',
      hint: 'Add a sphere',
      icon: '●',
      contexts: ['empty', 'always'],
      enabled: () => true,
      run: async () => { await host.addPrimitive('sphere'); },
    },

    // ---------------------------------------------------------------- modify
    {
      id: 'modify.edge',
      title: 'Modify edge',
      hint: 'Fillet or chamfer the selected edges',
      icon: '◟',
      contexts: ['edge'],
      sector: { edge: 0 },
      toolbar: { order: 30 },
      children: ['modify.fillet', 'modify.chamfer'],
      enabled: needsSelection('edge', 'one or more edges'),
      run: () => {},
    },
    {
      id: 'modify.fillet',
      title: 'Fillet',
      hint: 'Round the selected edges',
      icon: '◜',
      contexts: ['edge'],
      // Fit owns plain F: it is the far more frequent action, and it is what the status
      // bar has advertised since Phase 1.
      keys: ['shift+f'],
      enabled: needsSelection('edge', 'one or more edges'),
      run: async () => { await host.addEdgeOperation('fillet'); },
    },
    {
      id: 'modify.chamfer',
      title: 'Chamfer',
      hint: 'Bevel the selected edges',
      icon: '◹',
      contexts: ['edge'],
      keys: ['c'],
      enabled: needsSelection('edge', 'one or more edges'),
      run: async () => { await host.addEdgeOperation('chamfer'); },
    },
    {
      id: 'modify.body',
      title: 'Modify',
      hint: 'Hollow, mirror or move the body',
      icon: '◫',
      // Also on 'face': shell and draft both act on picked faces, and right-clicking the
      // face you want to open is the natural way to reach them.
      contexts: ['body', 'face', 'always'],
      sector: { body: 0, face: 4 },
      toolbar: { order: 31 },
      children: ['modify.shell', 'modify.draft', 'modify.mirror', 'modify.move'],
      enabled: needsModel,
      run: () => {},
    },
    {
      id: 'modify.shell',
      title: 'Shell',
      hint: 'Hollow the body, opening the selected faces',
      icon: '⌷',
      contexts: ['face'],
      enabled: (s) => (s.selectionKind === 'face' && s.selectionCount > 0
        ? true : 'Select the faces to open'),
      run: async () => { await host.addSolidFeature('shell'); },
    },
    {
      id: 'modify.draft',
      title: 'Draft',
      hint: 'Taper the selected faces away from the plate',
      icon: '◺',
      contexts: ['face'],
      enabled: (s) => (s.selectionKind === 'face' && s.selectionCount > 0
        ? true : 'Select the faces to taper'),
      run: async () => { await host.addSolidFeature('draft'); },
    },
    {
      id: 'modify.mirror',
      title: 'Mirror',
      hint: 'Reflect the body and keep both halves',
      icon: '⇋',
      contexts: ['body'],
      enabled: needsModel,
      run: async () => { await host.addSolidFeature('mirror'); },
    },
    {
      id: 'modify.move',
      title: 'Move',
      hint: 'Offset a body',
      icon: '✥',
      contexts: ['body', 'face'],
      enabled: needsModel,
      run: async () => { await host.addMove(); },
    },

    {
      id: 'feature.hole',
      title: 'Hole',
      hint: 'Drill a sized hole from the fastener table',
      icon: '◎',
      contexts: ['face', 'always'],
      toolbar: { order: 33 },
      keys: ['h'],
      enabled: needsModel,
      run: async () => { await host.addSolidFeature('hole'); },
    },
    {
      id: 'pattern.new',
      title: 'Pattern',
      hint: 'Repeat the body in a row or around an axis',
      icon: '⁘',
      contexts: ['body', 'always'],
      toolbar: { order: 34 },
      children: ['pattern.linear', 'pattern.circular'],
      enabled: needsModel,
      run: () => {},
    },
    {
      id: 'pattern.linear',
      title: 'Linear',
      hint: 'Repeat along a direction',
      icon: '⋯',
      contexts: ['body'],
      enabled: needsModel,
      run: async () => { await host.addSolidFeature('linearPattern'); },
    },
    {
      id: 'pattern.circular',
      title: 'Circular',
      hint: 'Repeat around an axis',
      icon: '⊛',
      contexts: ['body'],
      enabled: needsModel,
      run: async () => { await host.addSolidFeature('circularPattern'); },
    },

    // ---------------------------------------------------------------- combine
    {
      id: 'boolean.combine',
      title: 'Combine',
      hint: 'Cut, fuse or intersect two bodies',
      icon: '⊕',
      contexts: ['body', 'always'],
      sector: { body: 2 },
      toolbar: { order: 40 },
      children: ['boolean.cut', 'boolean.union', 'boolean.intersect'],
      enabled: (s) => (s.bodyCount >= 2 ? true : 'Needs two separate bodies'),
      run: () => {},
    },
    {
      id: 'boolean.cut',
      title: 'Cut',
      hint: 'Subtract the last body from the one before it',
      icon: '⊖',
      contexts: ['body', 'always'],
      enabled: (s) => (s.bodyCount >= 2 ? true : 'Needs two separate bodies'),
      run: async () => { await host.addBoolean('cut'); },
    },
    {
      id: 'boolean.union',
      title: 'Union',
      hint: 'Fuse the last two bodies',
      icon: '⊕',
      contexts: ['body', 'always'],
      enabled: (s) => (s.bodyCount >= 2 ? true : 'Needs two separate bodies'),
      run: async () => { await host.addBoolean('union'); },
    },
    {
      id: 'boolean.intersect',
      title: 'Intersect',
      hint: 'Keep only where the last two bodies overlap',
      icon: '⊗',
      contexts: ['body'],
      enabled: (s) => (s.bodyCount >= 2 ? true : 'Needs two separate bodies'),
      run: async () => { await host.addBoolean('intersect'); },
    },

    // ---------------------------------------------------------------- tree
    {
      id: 'feature.delete',
      title: 'Delete',
      hint: 'Remove the focused feature',
      icon: '␡',
      contexts: ['tree-item', 'body'],
      sector: { 'tree-item': 0 },
      keys: ['delete'],
      enabled: (s) => (s.focusedFeature ? true : 'Select a feature in the tree'),
      run: async () => { await host.deleteFocused(); },
    },
    {
      id: 'feature.suppress',
      title: 'Suppress',
      hint: 'Skip this feature without deleting it',
      icon: '⊘',
      contexts: ['tree-item'],
      sector: { 'tree-item': 2 },
      enabled: (s) => (s.focusedFeature ? true : 'Select a feature in the tree'),
      run: async () => { await host.suppressFocused(true); },
    },

    // ---------------------------------------------------------------- view
    {
      id: 'view.fit',
      title: 'Fit',
      hint: 'Frame the whole model',
      icon: '⤢',
      contexts: ['empty', 'always'],
      sector: { empty: 6 },
      keys: ['f'],
      enabled: needsModel,
      run: () => host.fitAll(),
    },
    {
      id: 'view.lookAt',
      title: 'Look at face',
      hint: 'Square the camera to the selected face',
      icon: '⊙',
      contexts: ['face'],
      sector: { face: 2 },
      enabled: needsSelection('face', 'a face'),
      run: () => { host.lookAtSelection(); },
    },
    {
      id: 'view.pivot',
      title: 'Pivot here',
      hint: 'Orbit around this point',
      icon: '✜',
      contexts: ['face', 'edge', 'vertex'],
      sector: { face: 6, edge: 2, vertex: 0 },
      keys: ['.'],
      enabled: (s) => (s.hoverKind || s.selectionCount ? true : 'Point at the model first'),
      run: () => { host.pivotToSelection(); },
    },

    // ---------------------------------------------------------------- document
    {
      id: 'edit.undo',
      title: 'Undo',
      icon: '↶',
      contexts: ['always'],
      keys: ['ctrl+z'],
      enabled: (s) => (s.canUndo ? true : 'Nothing to undo'),
      run: () => host.undo(),
    },
    {
      id: 'edit.redo',
      title: 'Redo',
      icon: '↷',
      contexts: ['always'],
      keys: ['ctrl+shift+z', 'ctrl+y'],
      enabled: (s) => (s.canRedo ? true : 'Nothing to redo'),
      run: () => host.redo(),
    },
    {
      id: 'file.export',
      title: 'Export STL',
      hint: 'Save the model as an STL for slicing',
      icon: '⭳',
      contexts: ['always'],
      toolbar: { order: 90, pin: 'end' },
      keys: ['ctrl+e'],
      enabled: (s) => (s.hasModel ? true : 'Nothing to export yet'),
      run: () => host.exportStl(),
    },
    {
      id: 'select.cycleFilter',
      title: 'Selection filter',
      hint: 'Cycle face / edge / vertex / body',
      icon: '⧉',
      contexts: ['always'],
      keys: ['tab'],
      enabled: () => true,
      run: () => host.cycleSelectionFilter(1),
    },
    {
      id: 'select.clear',
      title: 'Clear selection',
      icon: '⨯',
      contexts: ['always', 'edge'],
      sector: { edge: 6 },
      keys: ['escape'],
      enabled: (s) => (s.selectionCount > 0 ? true : 'Nothing selected'),
      run: () => host.clearSelection(),
    },
    {
      id: 'app.about',
      title: 'CARDstock',
      hint: 'What the name means, and which build this is',
      icon: '◈',
      contexts: ['always'],
      toolbar: { order: 91, pin: 'end', compact: true },
      enabled: () => true,
      run: () => host.openAbout(),
    },
    {
      id: 'app.palette',
      title: 'Command palette',
      hint: 'Search every command',
      icon: '⌘',
      contexts: ['always'],
      keys: ['ctrl+k'],
      enabled: () => true,
      run: () => host.openPalette(),
    },
  ];
}
